apiVersion: v1
kind: Secret
metadata:
  name: ${component}-ca-cert
  namespace: karmada-system
type: kubernetes.io/tls
data:
  tls.crt: |
    ${ca_crt}
  tls.key: |
    ${ca_key}

#   * 作用：存储根证书 (CA) 的公私钥。
#   * 详细解释：
#       * 这个 Secret 的类型是 kubernetes.io/tls，但它的用途非常特殊。它包含了整个 Karmada 集群的根证书颁发机构 (CA) 的证书 (`tls.crt`) 和私钥 (`tls.key`)。
#       * 拥有 CA 的私钥意味着拥有了签发新证书的能力。
#       * 在 Karmada 中，这个 Secret 主要提供给 kube-controller-manager。kube-controller-manager 内部有一个 csrsigning 控制器，它需要使用 CA
#         的私钥来签署新的证书签名请求（CSRs），例如在有新的集群以 PULL 模式加入时，为其 karmada-agent 签发客户端证书。
#   * 一句话总结：让一个组件扮演证书颁发机构（CA）的角色，赋予其签发证书的权力。这是一个权限非常高的 Secret。