apiVersion: v1
kind: Secret
metadata:
  name: ${name}-cert
  namespace: karmada-system
type: kubernetes.io/tls
data:
  ca.crt: |
    ${ca_crt}
  tls.crt: |
    ${tls_crt}
  tls.key: |
    ${tls_key}

#    * 作用：存储一个组件的服务端或客户端证书。
#   * 详细解释：
#       * 这是最标准的 TLS Secret。它包含了一个组件进行 mTLS (双向认证) 通信所需的所有凭证。
#       * ca.crt: 根 CA 的公共证书。用于验证通信对方提供的证书是否是由可信的 CA 签发的。
#       * tls.crt: 组件自身的证书。当作为服务端时，它会将此证书提供给客户端以证明自己的身份。
#       * tls.key: 组件证书对应的私钥。用于解密客户端发来的信息和签名。
#       * 这个 Secret 会被挂载到组件的 Pod 中。例如，karmada-apiserver 会使用它来对外提供 HTTPS 服务；karmada-webhook 也会用它来建立安全的 Webhook 服务。
#   * 一句话总结：为一个组件提供身份标识，使其能作为 TLS 通信中的服务端或客户端。